ld:
  host: 39.103.154.159
  mysql-port: 3306
  nacos-port: 8848
  redis-port: 6379
  rocketmq-port:
  druid_password: 
    
nacos: 
  #dev
  namespace: bf526873-2af9-498a-9d66-7199b529b45a

#database
DB_HOST: ${ld.host}:${ld.mysql-port}
DB_NAME: ldb
DB_USERNAME: root
DB_PASSWORD: 